name       : haskell-hspec-discover
version    : 2.7.1
release    : 3
source     :
    - https://hackage.haskell.org/package/hspec-discover-2.7.1/hspec-discover-2.7.1.tar.gz : 0b31c29b37d7d446d44b3559f794cd62b09ee5fc3f30862eccd8284e52758764
license    : MIT
component  : programming.haskell
summary    : Automatically discover and run Hspec tests
description: |
    Automatically discover and run Hspec tests
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
