name       : haskell-hspec-discover
version    : 2.5.1
release    : 2
source     :
    - https://hackage.haskell.org/package/hspec-discover-2.5.1/hspec-discover-2.5.1.tar.gz : 3c187d35b400b1e22ba9f98d76c94dad8368e2a915ba087509316dd7252a7228
license    : MIT
component  : programming.haskell
summary    : Automatically discover and run Hspec tests
description: "Automatically discover and run Hspec tests \n"
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
