name       : haskell-hspec-discover
version    : 2.4.2
release    : 1
source     :
    - http://hackage.haskell.org/package/hspec-discover-2.4.2/hspec-discover-2.4.2.tar.gz : 8c9ad7bc21eabcc28526e8fd8e12927c0d659c9b3179e665c30b175fa5011d2c
license    : MIT
component  : programming.haskell
summary    : Automatically discover and run Hspec tests 
description: |
    Automatically discover and run Hspec tests 
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
